from . import res_users
from . import res_partner
from . import mail_message
from . import script
from . import script_step
from . import discuss_channel
from . import page_sleepy_chat
from . import page_about
from . import article
