from . import res_users
from . import res_partner
from . import mail_message
from . import script
from . import script_step
from . import discuss_channel
from . import chat
from . import about
from . import article
from . import base
from . import ritual
from . import ritual_line
from . import ir_http
from . import settings
from . import statistic
